name: Build, Scan, and Publish Docker Image

on:
  push:
    branches:
      - main

jobs:
  build-scan-publish:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Log in to the GitHub Container Registry
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # Build the Docker image
      - name: Build Docker image
        run: |
          docker build -t ghcr.io/${{ github.repository_owner }}/ue19-lab-05:latest .

      # Scan the Docker image for vulnerabilities
      - name: Scan Docker image with Trivy
        uses: aquasecurity/trivy-action@v0.28.0
        with:
          image-ref: ghcr.io/${{ github.repository_owner }}/ue19-lab-05:latest
          severity: HIGH,CRITICAL

      # Push the Docker image to GitHub Container Registry
      - name: Push Docker image to GitHub Packages
        if: success()
        run: |
          docker push ghcr.io/${{ github.repository_owner }}/ue19-lab-05:latest
